#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 14 09:20:27 ICT 2026
maven-metadata-Eclipse\ Repository.xml.error=
maven-metadata-Eclipse\ Repository.xml.lastUpdated=1778724165015
maven-metadata-github-jda.xml.lastUpdated=1778725227893
maven-metadata-github-jda.xml/4f7098dcfb4c2b1e509f5bccb54fb597d14d9daa@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778724165016
maven-metadata-github-jda.xml/756f449b285ecf9883836b201d2f78de407a269d@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778662770658
maven-metadata-github-jda.xml/98ec33cf6bca8ec2bbae3b61701a56b4e98195b8@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778662748468
maven-metadata-github-jda.xml/@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778660550651
maven-metadata-local-maven-repo.xml.error=
maven-metadata-local-maven-repo.xml.lastUpdated=1778724165015
