#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed May 13 16:03:49 ICT 2026
maven-metadata-Eclipse\ Repository.xml.error=
maven-metadata-Eclipse\ Repository.xml.lastUpdated=1778660549758
maven-metadata-github-jda.xml.lastUpdated=1778663029982
maven-metadata-github-jda.xml/756f449b285ecf9883836b201d2f78de407a269d@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778662769152
maven-metadata-github-jda.xml/98ec33cf6bca8ec2bbae3b61701a56b4e98195b8@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778662746463
maven-metadata-github-jda.xml/@default-github-jda-https\://maven.pkg.github.com/jdomainapp/jda/.lastUpdated=1778660549762
maven-metadata-local-maven-repo.xml.error=
maven-metadata-local-maven-repo.xml.lastUpdated=1778660549757
